<?php
/**
 * @file
 * Contains install and update functions for Views Reveal.
 */

/**
 * Implements hook_module_enable().
 */
function views_reveal_enable() {
  $lib = libraries_get_path('reveal');
  if (empty($lib)) {
    drupal_set_message('<h3>' .
    t('The <a href=@revealjs>Reveal.js library</a> is required to use this module.', array('@revealjs' => 'https://github.com/hakimel/reveal.js'))
    . '</h3>', 'warning');
  }
}
